jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 180
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      GHC 8.6:
        ARGS: "--stack-yaml stack-old.yaml --resolver lts-14"
      GHC 8.8:
        ARGS: "--resolver lts-16"
      GHC 8.10:
        ARGS: "--resolver lts-17"
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -sSL https://get.haskellstack.org/ | sh -s - -f
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
