jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      GHC 8.6:
        ARGS: "--stack-yaml stack-old.yaml --resolver lts-14"
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack $ARGS test --bench --no-run-benchmarks
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
